[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip"]

[phases.build]
cmds = [
  "pip install --upgrade pip",
  "pip install -r backend/requirements.txt",
  "npm install"
]

[start]
cmd = "python3 -m uvicorn backend.main:app --host 0.0.0.0 --port 8080"