[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python311",
  "python311Packages.pip",
  "python311Packages.fastapi",
  "python311Packages.uvicorn",
  "python311Packages.pydantic",
  "python311Packages.requests"
]

[phases.build]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install --break-system-packages -r backend/requirements.txt",
  "npm install"
]

[start]
cmd = "python3 -m uvicorn backend.main:app --host 0.0.0.0 --port 8080"