[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip", "python311Packages.uvicorn", "python311Packages.fastapi"]

[phases.build]
cmds = [
  "pip install --upgrade pip --user",
  "pip install -r backend/requirements.txt --user",
  "npm install"
]

[start]
cmd = "python3 -m uvicorn backend.main:app --host 0.0.0.0 --port 8080"