[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python310",
  "python310Packages.pip",
  "python310Packages.virtualenv"
]

[phases.build]
cmds = [
  "python3.10 -m venv /app/venv",
  "source /app/venv/bin/activate",
  "/app/venv/bin/python -m pip install --upgrade pip",
  "/app/venv/bin/python -m pip install --no-cache-dir -r backend/requirements.txt",
  "npm install"
]

[start]
cmd = "source /app/venv/bin/activate && /app/venv/bin/python -m uvicorn backend.main:app --host 0.0.0.0 --port 8080"