[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python310", 
  "python310Packages.pip"
]

[phases.build]
cmds = [
  "python3 -m venv /app/venv",
  "/app/venv/bin/python -m pip install --upgrade pip",
  "/app/venv/bin/python -m pip install --no-cache-dir -r backend/requirements.txt",
  "npm install"
]

[start]
cmd = "/app/venv/bin/python -m uvicorn backend.main:app --host 0.0.0.0 --port 8080"