[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python311",
  "python311Packages.fastapi",
  "python311Packages.uvicorn",
  "python311Packages.pydantic",
  "python311Packages.requests",
  "python311Packages.setuptools",
  "python311Packages.wheel",
  "python311Packages.pip"
]

[phases.build]
cmds = [
  "npm install"
]

[start]
cmd = "python3 -m uvicorn backend.main:app --host 0.0.0.0 --port 8080"