[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python311",
  "python311Packages.virtualenv"
]

[phases.build]
cmds = [
  "python3 -m venv /app/venv",  # ✅ Create a Virtual Environment
  "source /app/venv/bin/activate",  # ✅ Activate Virtual Environment
  "pip install --no-cache-dir --upgrade pip",  # ✅ Upgrade pip *inside venv*
  "pip install --no-cache-dir -r backend/requirements.txt",  # ✅ Install dependencies
  "npm install"
]

[start]
cmd = "source /app/venv/bin/activate && python3 -m uvicorn backend.main:app --host 0.0.0.0 --port 8080"